probes:
  - name: latency
    type: std_fping
    output:
      - vodka

    groups:
      - name: public_dns
        hosts:
          - host: 8.8.8.8
            name: Google
            color: red
          - host: 4.2.2.1
            name: Level(3)
            color: blue
          - host: 208.67.222.222
            name: OpenDNS
            color: orange
          - host: 1.1.1.1
            name: Cloudflare
            color: purple
      - name: home
        hosts:
          - host: 192.168.3.1
            name: rt1
            color: red
          - host: 192.168.3.36
            name: st
            color: blue

  # mtr probe
  - name: mtr
    type: fping_mtr

    # we need to let graphsrv know what the default
    # graph to render data from this probe should be,
    # in this case we want it to be `mtr`
    default_graph: mtr

    # we need to let graphsrv know what data group
    # to use for data from this probe. Since the probe
    # itself is not setting up any groups unlike the `fping`
    # probe.
    group: mtr.cloudflare_dns

    # target host for the mtr probe
    host: 1.1.1.1

    output:
      - vodka


plugins:
  - name: std_fping
    type: fping
    count: 10
    interval: 5s
    output:
      - vodka


  # mtr plugin
  - name: fping_mtr
    type: fping_mtr
    interval: 5s


  - name: vodka
    type: vodka

    data:
      - type: fping
        handlers:
          - type: index
            index: host
          - type: store
            container: list
            limit: 500
      - type: fping_mtr
        handlers:
          - type: index
            index: host
          - type: store
            container: list
            limit: 100

    apps:
      graphsrv:
        enabled: true
        # point to custom layout config
        layout_config_file: examples/custom_layout/layouts.yaml
        graphs:
          multitarget:
            id_field: host
            type: multitarget
            plot_y: avg
            format_y: ms

          smokestack:
            id_field: host
            type: smokestack
            plot_y: avg

          mtr:
            id_field: host
            type: mtr


    plugins:
      - name: http
        type: flask
        bind: 0.0.0.0:7021
        debug: true
        static_url_path: /static
        server: self
        async: thread
        routes:
          /targets : graphsrv->targets
          /graph_data :
            methods:
              - POST
              - GET
            target: graphsrv->graph_data
          /graph : graphsrv->graph_view
          /overview_read_file : graphsrv->overview_read_file
          /: graphsrv->overview_view


logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout

    #file:
    #  class: logging.FileHandler
    #  level: DEBUG
    #  formatter: simple
    #  filename: /home/dev/sandbox/vaping/vaping.log

  loggers:
    vaping:
      level: DEBUG
      handlers:
        - console
        #- file
    vodka:
      level: DEBUG
      handlers:
        - console
        #- file

